trigger: none
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: hello-world
          platforms:
            - name: windows
              driver: docker
              suites:
                - default

            - name: windows-vagrant
              driver: vagrant
              suites:
                - default

            - name: ubuntu-vagrant
              driver: vagrant
              suites:
                - default
