trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - .rubocop.yml
      - src
      - samples/cookbooks/hello-world
pr: none

variables:
  isPublishEnabled: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: hello-world
          platforms:
            - name: windows
              suites:
                - default

            - name: linux
              suites:
                - default
