trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/cookbooks/hello-world
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: hello-world
          instances:
            - default-windows
            - default-ubuntu
