trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/cookbooks/virtualbox
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: virtualbox
          instances:
            - default-windows
            - default-ubuntu
          pool: windows-hyperv
