trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/cookbooks/virtualbox
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: virtualbox
          instances:
            - 7-point-0-windows
            - 7-point-0-ubuntu-2004
            - 7-point-0-ubuntu-2204
            - 6-point-1-windows
            - 6-point-1-ubuntu-2004
            - 6-point-1-ubuntu-2204
