trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/cookbooks/virtualbox
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: virtualbox
          instances:
            - 7-2-windows-2022
            # - 7-2-ubuntu-2404
            # - 7-2-ubuntu-2204
            - 7-1-windows-2022
            # - 7-1-ubuntu-2404
            # - 7-1-ubuntu-2204
