trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/cookbooks/virtualbox
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: virtualbox
          instances:
            - 7-0-windows
            - 7-0-ubuntu
            - 6-1-windows
            - 6-1-ubuntu
