parameters:
  configurations: []
    # - name: string
    #   platforms:
    #     - name: string
    #       suites: [ string ]

stages:
  - stage: commit
    displayName: Commit

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - job: build_${{ replace(configuration.name, '-', '_') }}
          displayName: Build ${{ configuration.name }}

          pool:
            name: Default
            demands:
              - AZP_AGENT_DOCKER

          workspace:
            clean: all

          steps:
            - checkout: self
              submodules: recursive

            - script: |
                docker --version
                docker-compose --version

                docker image ls -a
                docker container ls -a
              displayName: Initialize Docker

            - script: |
                docker-compose run chef-cookbook-lint ${{ configuration.name }}
              displayName: Lint

            - script: |
                docker-compose run chef-cookbook-test ${{ configuration.name }}
              displayName: Test

            - script: |
                docker-compose down --rmi local --volumes
              displayName: Clean
              condition: always()

  - stage: acceptance
    displayName: Acceptance

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - ${{ each platform in configuration.platforms }}:
          - ${{ each suite in platform.suites }}:
            - job: test_${{ replace(configuration.name, '-', '_') }}_${{ replace(platform.name, '-', '_') }}_${{ replace(suite, '-', '_') }}
              displayName: Test ${{ configuration.name }} on ${{ platform.name }} for ${{ suite }}

              pool:
                name: Default
                demands:
                  - AZP_AGENT_CHEF
                  - AZP_AGENT_VAGRANT

              workspace:
                clean: all

              steps:
                - checkout: self
                  submodules: recursive

                - script: |
                    vagrant --version
                    vagrant plugin list

                    vagrant box list
                    vagrant global-status
                  displayName: Initialize Vagrant

                - script: |
                    cd samples/cookbooks/${{ configuration.name }}
                    kitchen test ${{ suite }}-${{ platform.name }}
                  displayName: Test

                - script: |
                    cd samples/cookbooks/${{ configuration.name }}
                    kitchen destroy ${{ suite }}-${{ platform.name }}
                  displayName: Clean
                  condition: always()
