parameters:
  configurations: []
    # - name: string
    #   instances: [ string ]

stages:
  - stage: commit
    displayName: Commit

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - job: build_${{ replace(configuration.name, '-', '_') }}
          displayName: Build ${{ configuration.name }}

          pool:
            name: default
            demands:
              - VSTS_AGENT_CAP_VIRTUALIZATION_PROVIDER

          steps:
            - checkout: self
              submodules: recursive

            - script: |
                chef --version
              displayName: Initialize Chef

            - script: |
                chef exec cookstyle ./samples/cookbooks/${{ configuration.name }}
              displayName: Lint

            - script: |
                chef exec rspec ./samples/cookbooks/${{ configuration.name }}
              displayName: Test

  - stage: acceptance
    displayName: Acceptance

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - ${{ each instance in configuration.instances }}:
          - job: test_${{ replace(configuration.name, '-', '_') }}_${{ replace(instance, '-', '_') }}
            displayName: Test ${{ configuration.name }} on ${{ instance }}

            pool:
              name: default
              demands:
                - VSTS_AGENT_CAP_VIRTUALIZATION_PROVIDER

            steps:
              - checkout: self
                submodules: recursive

              - script: |
                  chef --version
                displayName: Initialize Chef

              - script: |
                  vagrant --version
                  vagrant plugin list

                  vagrant box list
                  vagrant global-status --prune
                displayName: Initialize Vagrant

              - script: |
                  cd ./samples/cookbooks/${{ configuration.name }}
                  kitchen test ${{ instance }}
                displayName: Test

              - script: |
                  cd ./samples/cookbooks/${{ configuration.name }}
                  kitchen create ${{ instance }}
                displayName: Create
                condition: failed()

              - script: |
                  cd ./samples/cookbooks/${{ configuration.name }}
                  kitchen destroy ${{ instance }}
                displayName: Clean
                condition: always()
