parameters:
  configurations: []
    # - name: string
    #   platforms:
    #     - name: string
    #       suites: [ string ]

stages:
  - stage: commit
    displayName: Commit

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - job: build_${{ replace(configuration.name, '-', '_') }}
          displayName: Build ${{ configuration.name }}

          pool:
            name: Default
            demands:
              - AZP_AGENT_CHEF

          workspace:
            clean: all

          steps:
            - checkout: self
              submodules: recursive

            - script: |
                chef --version
              displayName: Initialize Chef

            - script: |
                chef exec cookstyle ./samples/cookbooks/${{ configuration.name }}
              displayName: Lint

            - script: |
                chef exec rspec ./samples/cookbooks/${{ configuration.name }}
              displayName: Test

  - stage: acceptance
    displayName: Acceptance
    condition: and(succeeded(), eq(variables.isPublishEnabled, 'true'))

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - ${{ each platform in configuration.platforms }}:
          - ${{ each suite in platform.suites }}:
            - job: test_${{ replace(configuration.name, '-', '_') }}_${{ replace(platform.name, '-', '_') }}_${{ replace(suite, '-', '_') }}
              displayName: Test ${{ configuration.name }} on ${{ platform.name }} for ${{ suite }}

              # pool:
              #   name: Default
              #   demands:
              #     - AZP_AGENT_CHEF
              #     - AZP_AGENT_VAGRANT

              pool:
                name: windows

              workspace:
                clean: all

              steps:
                - checkout: self
                  submodules: recursive

                - script: |
                    chef --version
                  displayName: Initialize Chef

                - script: |
                    vagrant --version
                    vagrant plugin list

                    vagrant box list
                    vagrant global-status
                  displayName: Initialize Vagrant

                - script: |
                    cd samples/cookbooks/${{ configuration.name }}
                    kitchen test ${{ suite }}-${{ platform.name }}
                  displayName: Test

                - script: |
                    cd samples/cookbooks/${{ configuration.name }}
                    kitchen destroy ${{ suite }}-${{ platform.name }}
                  displayName: Clean
                  condition: always()
