parameters:
  configurations: []
    # - name: string
    #   instances: [ string ]

stages:
  - stage: commit
    displayName: Commit

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - job: build_${{ replace(configuration.name, '-', '_') }}
          displayName: Build cookbook ${{ configuration.name }}

          pool:
            vmImage: ubuntu-22.04

          steps:
            - checkout: self
              submodules: recursive

            - script: |
                curl -Ls https://gist.github.com/gusztavvargadr/1f0d7dddc7f48549368eaaedf19bfe55/raw/deploy.sh | sudo POLICY_NAME="chef-workstation" bash -s
                chef --version
              displayName: Initialize Chef

            - script: |
                chef exec cookstyle ./samples/cookbooks/${{ configuration.name }}
              displayName: Lint

            - script: |
                chef exec rspec ./samples/cookbooks/${{ configuration.name }}
              displayName: Test

  - stage: acceptance
    displayName: Acceptance

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - ${{ each instance in configuration.instances }}:
          - job: test_${{ replace(configuration.name, '-', '_') }}_${{ replace(instance, '-', '_') }}
            displayName: Test cookbook ${{ configuration.name }} on instance ${{ instance }}

            pool:
              name: default
              demands:
                - VSTS_AGENT_CAP_VIRTUALIZATION_PROVIDER

            steps:
              - checkout: self
                submodules: recursive

              - script: |
                  chef --version
                displayName: Initialize Chef

              - script: |
                  vagrant --version
                  vagrant plugin list

                  vagrant box list
                  vagrant global-status --prune
                displayName: Initialize Vagrant

              - script: |
                  cd ./samples/cookbooks/${{ configuration.name }}
                  kitchen test ${{ instance }}
                displayName: Test

              - script: |
                  cd ./samples/cookbooks/${{ configuration.name }}
                  kitchen create ${{ instance }}
                displayName: Create
                condition: not(succeeded())

              - script: |
                  cd ./samples/cookbooks/${{ configuration.name }}
                  kitchen destroy ${{ instance }}
                displayName: Clean
                condition: always()
