parameters:
  configurations: []
    # - name: string
    #   platforms:
    #     - name: string
    #       driver: string
    #       suites: [ string ]

stages:
  - stage: commit
    displayName: Commit

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - job: build_${{ replace(configuration.name, '-', '_') }}
          displayName: Build ${{ configuration.name }}

          pool:
            vmImage: ubuntu-20.04

          workspace:
            clean: all

          steps:
            - checkout: self
              submodules: recursive

            - script: |
                docker --version
                docker-compose --version

                docker image ls -a
                docker container ls -a
              displayName: Initialize Docker

            - script: |
                chmod +x ./build/chef/linux/*.sh
                docker-compose pull --quiet chef-workstation-linux
              displayName: Restore

            - script: |
                docker-compose run chef-cookbook-lint-linux ${{ configuration.name }}
              displayName: Lint

            - script: |
                docker-compose run chef-cookbook-test-linux ${{ configuration.name }}
              displayName: Test

            - script: |
                docker-compose down --rmi local --volumes
              displayName: Clean
              condition: always()

  - stage: acceptance
    displayName: Acceptance

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - ${{ each platform in configuration.platforms }}:
          - ${{ each suite in platform.suites }}:
            - job: test_${{ replace(configuration.name, '-', '_') }}_${{ replace(platform.name, '-', '_') }}_${{ replace(suite, '-', '_') }}
              displayName: Test ${{ configuration.name }} on ${{ platform.name }} for ${{ suite }}

              ${{ if eq(platform.driver, 'vagrant') }}:
                pool:
                  name: Default
                  demands:
                    - AZP_AGENT_VAGRANT

              ${{ if eq(platform.driver, 'docker') }}:
                pool:
                  name: core-windows

              workspace:
                clean: all

              steps:
                - checkout: self
                  submodules: recursive

                - ${{ if eq(platform.driver, 'vagrant') }}:
                  - script: |
                      vagrant --version
                      vagrant plugin list

                      vagrant box list
                      vagrant global-status
                    displayName: Initialize Vagrant

                - ${{ if eq(platform.driver, 'docker') }}:
                  - script: |
                      docker --version
                      docker-compose --version

                      docker image ls -a
                      docker container ls -a
                    displayName: Initialize Docker

                  - script: |
                      docker-compose pull --quiet chef-workstation-${{ platform.name }}
                    displayName: Restore

                - script: |
                    cd samples/cookbooks/${{ configuration.name }}
                    kitchen test ${{ suite }}-${{ platform.name }}
                  displayName: Test
                  env:
                    KITCHEN_YAML: kitchen.${{ platform.driver }}.yml

                - script: |
                    cd samples/cookbooks/${{ configuration.name }}
                    kitchen destroy ${{ suite }}-${{ platform.name }}
                  displayName: Clean
                  env:
                    KITCHEN_YAML: kitchen.${{ platform.driver }}.yml
                  condition: always()
