driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    vagrantfiles:
      - ../vagrant.windows-server.rb

suites:
  - name: server
    run_list:
      - recipe[gusztavvargadr_iis_test::server]
