driver:
  name: vagrant
  vagrantfiles:
    - ../../../src/kitchen.vagrant
  provider: <%= ENV['VAGRANT_PREFERRED_PROVIDERS'] || ENV['VAGRANT_DEFAULT_PROVIDER'] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      box: <%= ENV['VAGRANT_BOX_WINDOWS_SERVER'] || 'gusztavvargadr/windows-server' %>

suites:
  - name: server
    run_list:
      - recipe[gusztavvargadr_iis_test::server]
