driver:
  name: vagrant
  vagrantfiles:
    - ../vagrant.rb

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows

suites:
  - name: server
    run_list:
      - recipe[gusztavvargadr_iis_test::server]
