driver:
  name: docker
  wait_for_transport: false

transport:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      image: gusztavvargadr/chef-client:windows
      run_options: --isolation process

suites:
  - name: server
    run_list:
      - recipe[gusztavvargadr_iis_test::server]
