driver:
  name: vagrant
  vagrantfiles:
    - ../../../src/kitchen.vagrant.rb

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      box: gusztavvargadr/windows-server

suites:
  - name: server
    run_list:
      - recipe[gusztavvargadr_iis_test::server]
