driver:
  name: docker
  wait_for_transport: false

transport:
  name: docker
  socket: tcp://localhost:2375

provisioner:
  name: chef_zero
  # product_name: chef
  # install_strategy: skip

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      image: gusztavvargadr/chef-client:windows-<%= ENV['KITCHEN_PLATFORM_WINDOWS_DOCKER_TAG'] %>
      run_options: --isolation process

suites:
  - name: server
    run_list:
      - recipe[gusztavvargadr_iis_test::server]
