trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/policies/development-virtualbox-tools
      - samples/cookbooks/virtualbox
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: development-virtualbox-tools
          instances:
            - default-windows
            - default-ubuntu
