trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/policies/development-virtualbox-tools
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: development-virtualbox-tools
          instances:
            - default-windows-2022
            - default-ubuntu-2404
            - default-ubuntu-2204
