version: '3'

services:
  chef-client-linux:
    image: gusztavvargadr/chef-client:linux
    build:
      context: ./build/docker/
      dockerfile: ./chef-client.linux.Dockerfile
    volumes:
      - ./:/opt/chef/

  chef-workstation-linux:
    image: gusztavvargadr/chef-workstation:linux
    build:
      context: ./build/docker/
      dockerfile: ./chef-workstation.linux.Dockerfile
    volumes:
      - ./:/opt/chef/

  chocolatey-cli-windows-ltsc2019:
    image: gusztavvargadr/chocolatey-cli:windows-ltsc2019
    build:
      context: ./build/docker/
      dockerfile: ./chocolatey-cli.windows.Dockerfile
      args:
        TAG: 'ltsc2019'
    volumes:
      - ./:C:/opt/chocolatey/

  chef-client-windows-ltsc2019:
    image: gusztavvargadr/chef-client:windows-ltsc2019
    build:
      context: ./build/docker/
      dockerfile: ./chef-client.windows.Dockerfile
      args:
        TAG: 'ltsc2019'
    volumes:
      - ./:C:/opt/chef/

  chef-workstation-windows-ltsc2019:
    image: gusztavvargadr/chef-workstation:windows-ltsc2019
    build:
      context: ./build/docker/
      dockerfile: ./chef-workstation.windows.Dockerfile
      args:
        TAG: 'ltsc2019'
    volumes:
      - ./:C:/opt/chef/

  chocolatey-cli-windows-1903:
    image: gusztavvargadr/chocolatey-cli:windows-1903
    build:
      context: ./build/docker/
      dockerfile: ./chocolatey-cli.windows.Dockerfile
      args:
        TAG: '1903'
    volumes:
      - ./:C:/opt/chocolatey/

  chef-client-windows-1903:
    image: gusztavvargadr/chef-client:windows-1903
    build:
      context: ./build/docker/
      dockerfile: ./chef-client.windows.Dockerfile
      args:
        TAG: '1903'
    volumes:
      - ./:C:/opt/chef/
