version: "3"

services:
  chef-client-linux:
    image: gusztavvargadr/chef-client:linux
    build:
      context: ./
      dockerfile: ./build/docker/linux/chef-client.Dockerfile
    volumes:
      - ./:/opt/docker/work/

  chef-workstation-linux:
    image: gusztavvargadr/chef-workstation:linux
    build:
      context: ./
      dockerfile: ./build/docker/linux/chef-workstation.Dockerfile
    volumes:
      - ./:/opt/docker/work/

  chef-policy-build-linux:
    image: gusztavvargadr/chef-workstation:linux
    volumes:
      - ./:/opt/docker/work/

  chef-policy-run-linux:
    image: gusztavvargadr/chef-client:linux
    volumes:
      - ./:/opt/docker/work/

  chef-client-windows:
    image: gusztavvargadr/chef-client:windows
    build:
      context: ./
      dockerfile: ./build/docker/windows/chef-client.Dockerfile
    volumes:
      - ./:C:/opt/docker/work/

  chef-workstation-windows:
    image: gusztavvargadr/chef-workstation:windows
    build:
      context: ./
      dockerfile: ./build/docker/windows/chef-workstation.Dockerfile
    volumes:
      - ./:C:/opt/docker/work/

  chef-policy-build-windows:
    image: gusztavvargadr/chef-workstation:windows
    volumes:
      - ./:C:/opt/docker/work/

  chef-policy-run-windows:
    image: gusztavvargadr/chef-client:windows
    volumes:
      - ./:C:/opt/docker/work/
