version: '3'

services:
  chef:
    build:
      context: ./build/docker/
      dockerfile: ./chef.Dockerfile
    volumes:
      - ./:/opt/chef/
      - ./.chef-workstation/:/root/.chef-workstation/

  chef-client-linux:
    build:
      context: ./build/docker/
      dockerfile: ./chef-client-linux.Dockerfile
    volumes:
      - ./:/opt/chef/
      - ./.chef-workstation/:/root/.chef-workstation/

  chef-client-windows:
    build:
      context: ./build/docker/
      dockerfile: ./chef-client-windows.Dockerfile
    volumes:
      - ./:C:/opt/chef/

  chef-policy:
    build:
      context: ./
      dockerfile: ./build/docker/chef-policy.Dockerfile
      args:
        directory: core
        policy: init
    volumes:
      - ./.chef/:/opt/chef/.chef/

  chocolatey-package:
    build:
      context: ./
      dockerfile: ./build/docker/chocolatey-package.Dockerfile
      args:
        directory: core
        policy: init
    volumes:
      - ./:C:/opt/chef/
