version: "3"

services:
  chef-core-linux:
    image: gusztavvargadr/chef-core:linux
    build:
      context: ./
      dockerfile: ./build/docker/linux/chef-core.Dockerfile
    volumes:
      - ./:/opt/docker/work/
    entrypoint: echo
    command: chef-core

  chef-client-linux:
    image: gusztavvargadr/chef-client:linux
    build:
      context: ./
      dockerfile: ./build/docker/linux/chef-client.Dockerfile
    volumes:
      - ./:/opt/docker/work/
    entrypoint: chef-client
    command: --version

  chef-workstation-linux:
    image: gusztavvargadr/chef-workstation:linux
    build:
      context: ./
      dockerfile: ./build/docker/linux/chef-workstation.Dockerfile
    volumes:
      - ./:/opt/docker/work/
    entrypoint: chef
    command: --version

  chef-cookbook-lint-linux:
    image: gusztavvargadr/chef-workstation:linux
    volumes:
      - ./:/opt/docker/work/
    entrypoint: ./build/chef/linux/chef-workstation.cookbook-lint.sh
    command: hello-world

  chef-cookbook-test-linux:
    image: gusztavvargadr/chef-workstation:linux
    volumes:
      - ./:/opt/docker/work/
    entrypoint: ./build/chef/linux/chef-workstation.cookbook-test.sh
    command: hello-world

  chef-policy-build-linux:
    image: gusztavvargadr/chef-workstation:linux
    volumes:
      - ./:/opt/docker/work/
    entrypoint: ./build/chef/linux/chef-workstation.policy-build.sh
    command: hello-world

  chef-policy-run-linux:
    image: gusztavvargadr/chef-client:linux
    volumes:
      - ./:/opt/docker/work/
    entrypoint: ./build/chef/linux/chef-client.policy-run.sh
    command: hello-world

  chef-core-windows:
    image: gusztavvargadr/chef-core:windows
    build:
      context: ./
      dockerfile: ./build/docker/windows/chef-core.Dockerfile
    volumes:
      - ./:C:/opt/docker/work/
    entrypoint: cmd
    command: /c echo chef-core

  chef-client-windows:
    image: gusztavvargadr/chef-client:windows
    build:
      context: ./
      dockerfile: ./build/docker/windows/chef-client.Dockerfile
    volumes:
      - ./:C:/opt/docker/work/
    entrypoint: chef-client.bat
    command: --version

  chef-workstation-windows:
    image: gusztavvargadr/chef-workstation:windows
    build:
      context: ./
      dockerfile: ./build/docker/windows/chef-workstation.Dockerfile
    volumes:
      - ./:C:/opt/docker/work/
    entrypoint: chef-cli.bat
    command: --version

  chef-cookbook-lint-windows:
    image: gusztavvargadr/chef-workstation:windows
    volumes:
      - ./:C:/opt/docker/work/
    entrypoint: powershell -File ./build/chef/windows/chef-workstation.cookbook-lint.ps1
    command: hello-world

  chef-cookbook-test-windows:
    image: gusztavvargadr/chef-workstation:windows
    volumes:
      - ./:C:/opt/docker/work/
    entrypoint: powershell -File ./build/chef/windows/chef-workstation.cookbook-test.ps1
    command: hello-world

  chef-policy-build-windows:
    image: gusztavvargadr/chef-workstation:windows
    volumes:
      - ./:C:/opt/docker/work/
    entrypoint: powershell -File ./build/chef/windows/chef-workstation.policy-build.ps1
    command: hello-world

  chef-policy-run-windows:
    image: gusztavvargadr/chef-client:windows
    volumes:
      - ./:C:/opt/docker/work/
    entrypoint: powershell -File ./build/chef/windows/chef-client.policy-run.ps1
    command: hello-world
