version: "3"

services:
  chef-client-linux:
    image: gusztavvargadr/chef-client:linux
    build:
      context: ./build/docker/
      dockerfile: ./chef-client.linux.Dockerfile
    volumes:
      - ./:/opt/chef/
    entrypoint: chef-client
    command: --help

  chef-workstation-linux:
    image: gusztavvargadr/chef-workstation:linux
    build:
      context: ./build/docker/
      dockerfile: ./chef-workstation.linux.Dockerfile
    volumes:
      - ./:/opt/chef/
    entrypoint: chef
    command: --help

  chocolatey-cli-windows:
    image: gusztavvargadr/chocolatey-cli:windows
    build:
      context: ./build/docker/
      dockerfile: ./chocolatey-cli.windows.Dockerfile
    isolation: process
    volumes:
      - ./:C:/opt/chocolatey/
    entrypoint: choco
    command: --help

  chef-client-windows:
    image: gusztavvargadr/chef-client:windows
    build:
      context: ./build/docker/
      dockerfile: ./chef-client.windows.Dockerfile
    isolation: process
    volumes:
      - ./:C:/opt/chef/
    entrypoint: chef-client.bat
    command: --help

  chef-workstation-windows:
    image: gusztavvargadr/chef-workstation:windows
    build:
      context: ./build/docker/
      dockerfile: ./chef-workstation.windows.Dockerfile
    isolation: process
    volumes:
      - ./:C:/opt/chef/
    entrypoint: chef-cli.bat
    command: --help
