services:
  chef-core:
    image: gusztavvargadr/chef-core:${PLATFORM_NAME}-${PLATFORM_VARIANT}-${PLATFORM_VERSION}
    build:
      context: ./
      dockerfile: ./build/docker/${PLATFORM_NAME}/chef-core.Dockerfile
      args:
        - PLATFORM_BASE

  chef-client:
    image: gusztavvargadr/chef-client:${PLATFORM_NAME}-${PLATFORM_VARIANT}-${PLATFORM_VERSION}
    build:
      context: ./
      dockerfile: ./build/docker/${PLATFORM_NAME}/chef-client.Dockerfile
      args:
        - PLATFORM_VARIANT
        - PLATFORM_VERSION

  chef-workstation:
    image: gusztavvargadr/chef-workstation:${PLATFORM_NAME}-${PLATFORM_VARIANT}-${PLATFORM_VERSION}
    build:
      context: ./
      dockerfile: ./build/docker/${PLATFORM_NAME}/chef-workstation.Dockerfile
      args:
        - PLATFORM_VARIANT
        - PLATFORM_VERSION
