trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/cookbooks/iis
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: iis
          instances:
            - default-windows-2022
