trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/cookbooks/iis
      - samples/cookbooks/windows
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: iis
          instances:
            - default-windows
