trigger: none
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: iis
          platforms:
            - name: windows
              driver: vagrant
              suites:
                - server-default
