trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'
  paths:
    include:
      - samples/cookbooks/iis
      - samples/cookbooks/iis_test
pr: none

stages:
  - template: ../../../build/azp/samples/cookbooks/stages.yml
    parameters:
      configurations:
        - cookbook: iis
          driver: docker
          platform: windows
          suites:
            - name: server
