pr: none

stages:
  - template: ../../../build/azp/samples/cookbooks/commit.yml
    parameters:
      options:
        - cookbook: iis

  - template: ../../../build/azp/samples/cookbooks/acceptance.yml
    parameters:
      options:
        - cookbook: iis
          suite: server
