trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/cookbooks/vsts
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: vsts
          instances:
            - default-windows-2022
            - default-ubuntu-2404
            - default-ubuntu-2204
            - destroy-windows-2022
            - destroy-ubuntu-2404
            - destroy-ubuntu-2204
