trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/cookbooks/vsts
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: vsts
          instances:
            - default-windows
            - default-ubuntu-2004
            - default-ubuntu-2204
            - destroy-windows
            - destroy-ubuntu-2004
            - destroy-ubuntu-2204
