trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - src
      - samples/policies/windows-core
pr: none

variables:
  isPublishEnabled: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: windows-core
          platforms:
            - windows
