trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/policies/windows-core
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: windows-core
          platforms:
            - default-windows
