trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/policies/core-ubuntu
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: core-ubuntu
          instances:
            - default-ubuntu-2404
            - default-ubuntu-2204
