---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../src/kitchen.vagrant
  provider: <%= ENV['VAGRANT_PREFERRED_PROVIDERS'] || ENV['VAGRANT_DEFAULT_PROVIDER'] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: w
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: chocolatey-packages
    run_list:
      - recipe[gusztavvargadr_windows_test::chocolatey_packages]
    attributes:
      gusztavvargadr_windows:
        chocolatey_packages:
          nuget.commandline:
          terraform:
            version: 0.8.8
          git:
            install:
              ignorechecksum:
              params: "'/GitAndUnixToolsOnPath /NoShellIntegration'"
          powershell:
            elevated: true
  - name: environment-variables
    run_list:
      - recipe[gusztavvargadr_windows_test::environment_variables]
    attributes:
      gusztavvargadr_windows:
        environment_variables:
          VARIABLE_USER:
            value: user
          VARIABLE_MACHINE:
            value: machine
            type: Machine
  - name: features
    run_list:
      - recipe[gusztavvargadr_windows_test::features]
    attributes:
      gusztavvargadr_windows:
        features:
          TelnetClient:
          IIS:
  - name: files
    run_list:
      - recipe[gusztavvargadr_windows_test::files]
    attributes:
      gusztavvargadr_windows:
        files:
          /Temp/hosts:
            source: file://C:/Windows/System32/drivers/etc/hosts
          /Temp/robots.txt:
            source: https://www.google.nl/robots.txt
  - name: native-packages
    run_list:
      - recipe[gusztavvargadr_windows_test::native_packages]
    attributes:
      gusztavvargadr_windows:
        native_packages:
          .NET Core SDK:
            source: https://download.microsoft.com/download/B/9/F/B9F1AF57-C14A-4670-9973-CDF47209B5BF/dotnet-dev-win-x64.1.0.4.exe
            install:
              - /install
              - /quiet
              - /norestart
            executable: C:/Program Files/dotnet/dotnet.exe
          SQL Server Management Studio 16:
            source: https://download.microsoft.com/download/9/3/3/933EA6DD-58C5-4B78-8BEC-2DF389C72BE0/SSMS-Setup-ENU.exe
            install:
              - /install
              - /quiet
              - /norestart
            executable: C:/Program Files (x86)/Microsoft SQL Server/130/Tools/Binn/ManagementStudio/Ssms.exe
            elevated: true
  - name: updates
    run_list:
      - recipe[gusztavvargadr_windows_test::updates]
