driver:
  name: docker
  wait_for_transport: false

transport:
  name: docker
  socket: tcp://localhost:2375

provisioner:
  name: chef_zero
  # product_name: chef
  # install_strategy: skip

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      dockerfile: ./windows.Dockerfile
      build_options: --build-arg TAG=<%= ENV['KITCHEN_PLATFORM_WINDOWS_DOCKER_TAG'] %>
      run_options: --isolation process

suites:
  - name: chocolatey-packages
    run_list:
      - recipe[gusztavvargadr_windows_test::chocolatey_packages]
    attributes:
      gusztavvargadr_windows:
        chocolatey_packages:
          # git:
          #   version: '2.24.0'
          #   install:
          #     params: '"/GitAndUnixToolsOnPath /NoAutoCrlf /NoShellIntegration"'
          #   elevated: true
          #   reboot: true
          conemu:
          far:

  - name: environment-variables
    run_list:
      - recipe[gusztavvargadr_windows_test::environment_variables]
    attributes:
      gusztavvargadr_windows:
        environment_variables:
          TEST_USER:
            value: Test User
          TEST_MACHINE:
            value: Test Machine
            type: Machine

  - name: node
    run_list:
      - recipe[gusztavvargadr_windows_test::node]

