driver:
  name: docker
  wait_for_transport: false

transport:
  name: docker
  socket: tcp://localhost:2375

provisioner:
  name: chef_zero
  # product_name: chef
  # install_strategy: skip

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      image: gusztavvargadr/chef-client:windows
      run_options: --isolation process

suites:
  - name: chocolatey-packages
    run_list:
      - recipe[gusztavvargadr_windows_test::chocolatey_packages]
    attributes:
      gusztavvargadr_windows:
        chocolatey_packages:
          # git:
          #   version: '2.24.0'
          #   install:
          #     params: '"/GitAndUnixToolsOnPath /NoAutoCrlf /NoShellIntegration"'
          #   elevated: true
          #   reboot: true
          conemu:
          far:

  - name: environment-variables
    run_list:
      - recipe[gusztavvargadr_windows_test::environment_variables]
    attributes:
      gusztavvargadr_windows:
        environment_variables:
          TEST_USER:
            value: Test User
          TEST_MACHINE:
            value: Test Machine
            type: Machine

  - name: features
    run_list:
      - recipe[gusztavvargadr_windows_test::features]
    attributes:
      gusztavvargadr_windows:
        features:
          TelnetClient:
          # Containers:
          #   reboot: true

  - name: files
    run_list:
      - recipe[gusztavvargadr_windows_test::files]
    attributes:
      gusztavvargadr_windows:
        files:
          /tmp/robots.txt:
            source: https://www.google.nl/robots.txt

  - name: native-packages
    run_list:
      - recipe[gusztavvargadr_windows_test::native_packages]
    attributes:
      gusztavvargadr_windows:
        native_packages:
          .NET Core SDK:
            source: https://download.microsoft.com/download/B/9/F/B9F1AF57-C14A-4670-9973-CDF47209B5BF/dotnet-dev-win-x64.1.0.4.exe
            install:
              - /install
              - /quiet
              - /norestart
            executable: C:/Program Files/dotnet/dotnet.exe
            elevated: true

  - name: updates
    run_list:
      - recipe[gusztavvargadr_windows_test::updates]
