driver:
  name: vagrant
  vm_hostname: false
  vagrantfiles:
    - ./kitchen.Vagrantfile

provisioner:
  name: chef_zero
  max_retries: 3
  wait_for_retry: 90

verifier:
  name: inspec

platforms:
  - name: windows-server
    driver:
      box: gusztavvargadr/windows-server
    transport:
      elevated: true

  - name: windows-10
    driver:
      box: gusztavvargadr/windows-10
    transport:
      elevated: true

  - name: ubuntu-server
    driver:
      box: gusztavvargadr/ubuntu-server

suites:
  - name: community
    attributes:
      gusztavvargadr_docker:
        engine:
          edition: community
        images:
          hello-world:
    includes:
      - ubuntu-server

  - name: desktop
    attributes:
      gusztavvargadr_docker:
        engine:
          edition: community
    includes:
      - windows-server
      - windows-10

  - name: enterprise
    attributes:
      gusztavvargadr_docker:
        engine:
          edition: enterprise
        images:
          hello-world:
    includes:
      - windows-server
