driver:
  name: vagrant
  vm_hostname: false
  vagrantfiles:
    - ./kitchen.Vagrantfile

verifier:
  name: inspec

platforms:
  - name: windows-server
    driver:
      box: gusztavvargadr/windows-server-core
    transport:
      elevated: true
    provisioner:
      max_retries: 1
      wait_for_retry: 30

  - name: windows-10
    driver:
      box: gusztavvargadr/windows-10
    transport:
      elevated: true
    provisioner:
      max_retries: 3
      wait_for_retry: 60

  - name: ubuntu
    driver:
      box: gusztavvargadr/ubuntu-server

suites:
  - name: community
    attributes:
      gusztavvargadr_docker:
        engine:
          edition: community
        images:
          hello-world:
    includes:
      - ubuntu

  - name: desktop
    attributes:
      gusztavvargadr_docker:
        engine:
          edition: desktop
    includes:
      - windows-10

  - name: enterprise
    attributes:
      gusztavvargadr_docker:
        engine:
          edition: enterprise
        images:
          hello-world:
    includes:
      - windows-server
