suites:
  - name: default
    provisioner:
      max_retries: 1
      wait_for_retry: 120
    attributes:
      gusztavvargadr_docker:
        tools:
          engine:latest-community:
        images:
          hello-world:
