provisioner:
  max_retries: 1
  wait_for_retry: 120

suites:
  - name: default
    attributes:
      gusztavvargadr_docker:
        tools:
          engine:latest-community:
        images:
          hello-world:
