driver:
  name: vagrant
  vm_hostname: false
  vagrantfiles:
    - ./kitchen.Vagrantfile

provisioner:
  max_retries: 0

verifier:
  name: inspec

platforms:
  - name: windows-2022
    driver:
      box: gusztavvargadr/kitchen-windows-2022
    transport:
      elevated: true
    provisioner:
      max_retries: 1
      wait_for_retry: 120

  - name: ubuntu-2404
    driver:
      box: gusztavvargadr/kitchen-ubuntu-2404

  - name: ubuntu-2204
    driver:
      box: gusztavvargadr/kitchen-ubuntu-2204

suites:
  - name: default
    attributes:
      gusztavvargadr_docker:
        tools:
          engine:latest-community:
        images:
          hello-world:
