driver:
  name: vagrant
  vagrantfiles:
    - ../../../src/kitchen.vagrant.rb

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      box: gusztavvargadr/windows-server

suites:
  - name: 2017-developer
    run_list:
      - recipe[gusztavvargadr_mssql_test::2017_developer]
  - name: 2017-ssms
    run_list:
      - recipe[gusztavvargadr_mssql_test::2017_ssms]
  - name: 2018-ssms
    run_list:
      - recipe[gusztavvargadr_mssql_test::2018_ssms]
