driver:
  name: docker
  wait_for_transport: false

transport:
  name: docker
  socket: tcp://localhost:2375

provisioner:
  name: chef_zero
  # product_name: chef
  # install_strategy: skip

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      image: gusztavvargadr/chef-client:windows-<%= ENV['KITCHEN_PLATFORM_WINDOWS_DOCKER_TAG'] %>
      run_options: --isolation process

suites:
  - name: 2017-developer
    run_list:
      - recipe[gusztavvargadr_mssql_test::2017_developer]

  - name: 2019-developer
    run_list:
      - recipe[gusztavvargadr_mssql_test::2019_developer]

  - name: 2017-ssms
    run_list:
      - recipe[gusztavvargadr_mssql_test::2017_ssms]

  - name: 2018-ssms
    run_list:
      - recipe[gusztavvargadr_mssql_test::2018_ssms]
