driver:
  name: vagrant
  vagrantfiles:
    - ../../../src/kitchen.vagrant
  provider: <%= ENV['VAGRANT_PREFERRED_PROVIDERS'] || ENV['VAGRANT_DEFAULT_PROVIDER'] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      box: <%= ENV['VAGRANT_BOX_WINDOWS_DESKTOP'] || 'gusztavvargadr/windows-10' %>

suites:
  - name: 2017-developer
    run_list:
      - recipe[gusztavvargadr_mssql_test::2017_developer]
  - name: 2017-ssms
    run_list:
      - recipe[gusztavvargadr_mssql_test::2017_ssms]
