require "#{File.dirname(__FILE__)}/../../../src/berkshelf"

gusztavvargadr_chef_sources

gusztavvargadr_chef_cookbook 'mssql_test'
gusztavvargadr_chef_cookbook 'mssql'

gusztavvargadr_chef_cookbook 'windows'
