driver:
  name: vagrant
  vagrantfiles:
    - ../vagrant.rb

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows

suites:
  - name: engine-community
    run_list:
      - recipe[gusztavvargadr_docker_test::engine_community]
  - name: engine-enterprise
    run_list:
      - recipe[gusztavvargadr_docker_test::engine_enterprise]
  - name: images
    run_list:
      - recipe[gusztavvargadr_docker_test::engine_enterprise]
      - recipe[gusztavvargadr_docker_test::images]
    attributes:
      gusztavvargadr_docker:
        images:
          hello-world:
