driver:
  name: vagrant
  vagrantfiles:
    - ../../../src/kitchen.vagrant.rb

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-base
    driver:
      box: gusztavvargadr/windows-server
  - name: windows-docker
    driver:
      box: gusztavvargadr/docker-windows
  - name: linux-base
    driver:
      box: gusztavvargadr/ubuntu-server
  - name: linux-docker
    driver:
      box: gusztavvargadr/docker-linux

suites:
  - name: engine-community
    run_list:
      - recipe[gusztavvargadr_docker_test::engine_community]
    includes:
      - windows-base
  - name: engine-enterprise
    run_list:
      - recipe[gusztavvargadr_docker_test::engine_enterprise]
    includes:
      - windows-base
  - name: images
    run_list:
      - recipe[gusztavvargadr_docker_test::images]
    attributes:
      gusztavvargadr_docker:
        images:
          hello-world:
    includes:
      - windows-docker
      - linux-docker
