driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      box: gusztavvargadr/windows-server
      vagrantfiles:
        - ../vagrant.rb

suites:
  - name: engine-community
    driver:
      box: gusztavvargadr/windows-10
    provisioner:
      named_run_list: engine_community

  - name: engine-enterprise
    provisioner:
      named_run_list: engine_enterprise

  - name: images
    provisioner:
      named_run_list: images
    attributes:
      gusztavvargadr_docker:
        images:
          hello-world:
