driver:
  name: vagrant

provisioner:
  name: chef_zero
  wait_for_retry: 180

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      box: gusztavvargadr/windows-server
      vagrantfiles:
        - ../vagrant.rb

suites:
  - name: engine-community
    driver:
      box: gusztavvargadr/windows-10
    run_list:
      - recipe[gusztavvargadr_docker_test::engine_community]

  - name: engine-enterprise
    run_list:
      - recipe[gusztavvargadr_docker_test::engine_enterprise]

  - name: images
    driver:
      box: gusztavvargadr/docker-windows
    run_list:
      - recipe[gusztavvargadr_docker_test::images]
    attributes:
      gusztavvargadr_docker:
        images:
          hello-world:
