driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-server
    driver:
      vagrantfiles:
        - ../vagrant.windows-server.rb

  - name: windows-10
    driver:
      vagrantfiles:
        - ../vagrant.windows-10.rb

  - name: docker-windows
    driver:
      vagrantfiles:
        - ../vagrant.docker-windows.rb

  - name: ubuntu
    driver:
      vagrantfiles:
        - ../vagrant.ubuntu-server.rb

suites:
  - name: engine-community
    provisioner:
      named_run_list: engine_community
    includes:
      - windows-10

  - name: engine-enterprise
    provisioner:
      named_run_list: engine_enterprise
    includes:
      - windows-server

  - name: images
    provisioner:
      named_run_list: images
    attributes:
      gusztavvargadr_docker:
        images:
          hello-world:
    includes:
      - docker-windows
