driver:
  name: vagrant
  vagrantfiles:
    - ../../../src/kitchen.vagrant
  provider: <%= ENV['VAGRANT_PREFERRED_PROVIDERS'] || ENV['VAGRANT_DEFAULT_PROVIDER'] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      box: <%= ENV['VAGRANT_BOX_DOCKER_WINDOWS'] || 'gusztavvargadr/docker-windows' %>
  - name: linux
    driver:
      box: <%= ENV['VAGRANT_BOX_DOCKER_LINUX'] || 'gusztavvargadr/docker-linux' %>

suites:
  - name: images
    run_list:
      - recipe[gusztavvargadr_docker_test::images]
    attributes:
      gusztavvargadr_docker:
        images:
          hello-world:
