driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      vagrantfiles:
        - ../vagrant.windows-server.rb


suites:
  - name: engine-community
    run_list:
      - recipe[gusztavvargadr_docker_test::engine_community]

  - name: engine-enterprise
    run_list:
      - recipe[gusztavvargadr_docker_test::engine_enterprise]

  - name: images
    run_list:
      - recipe[gusztavvargadr_docker_test::images]
    attributes:
      gusztavvargadr_docker:
        images:
          hello-world:
    driver:
      vagrantfiles:
        - ../vagrant.docker-windows.rb
