directory = File.dirname(__FILE__)

require "#{directory}/../../../src/berkshelf"

gusztavvargadr_chef_sources
gusztavvargadr_chef_cookbook 'docker_test'
gusztavvargadr_chef_cookbook 'docker'
gusztavvargadr_chef_cookbook 'windows'
