trigger:
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"
  paths:
    include:
      - samples/policies/core
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: windows
          policies:
            - core
