trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/cookbooks/development
      - samples/cookbooks/git
      - samples/cookbooks/dotnet
      - samples/cookbooks/docker
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: development
          instances:
            - default-windows-2022
            - default-ubuntu-2404
            - default-ubuntu-2204
