directory = File.dirname(__FILE__)

require "#{directory}/../../vagrant"

VagrantMachine.defaults_include(
  'box' => VagrantWindowsDesktopMachine.defaults['box'],
  'synced_folders' => {
    '/vagrant' => {
      'source' => '.',
      'disabled' => true,
    },
    '/src/gusztavvargadr/chef' => {
      'source' => "#{directory}/../../..",
    },
  },
  'provisioners' => {
    'chef_policyfile_install' => {},
  }
)

VagrantProvider.defaults_include(
  'memory' => 8192,
  'cpus' => 4
)

VagrantDeployment.configure(directory)
