trigger:
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"
  paths:
    include:
      - samples/cookbooks/vagrant
      - samples/cookbooks/vagrant_test
pr: none

stages:
  - template: ../../../build/azp/samples/cookbooks/stages.yml
    parameters:
      configurations:
        - cookbook: vagrant
          driver: vagrant
          platform: windows
          suites:
            - name: app
        - cookbook: vagrant
          driver: vagrant
          platform: ubuntu
          suites:
            - name: app
