trigger: none
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: vagrant
          platforms:
            - name: windows
              driver: vagrant
              suites:
                - default

            - name: ubuntu
              driver: vagrant
              suites:
                - default
