trigger: none
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: vagrant
          platforms:
            - name: windows
              suites:
                - default

            - name: linux
              suites:
                - default
