trigger: none
pr: none

stages:
  - template: ../../../build/azp/samples/cookbooks/stages.yml
    parameters:
      configurations:
        - cookbook: vagrant
          driver: docker
          platform: windows
          suites:
            - name: cli
