driver:
  name: vagrant
  vm_hostname: false
  vagrantfiles:
    - ./kitchen.Vagrantfile

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      box: gusztavvargadr/windows-server-core
    transport:
      elevated: true
    provisioner:
      max_retries: 1
      wait_for_retry: 30

  - name: ubuntu
    driver:
      box: gusztavvargadr/ubuntu-desktop

suites:
  - name: default
    attributes:
      gusztavvargadr_azure_pipelines:
        agent:
          version: "2.195.2"
