trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/policies/core-windows
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: core-windows
          instances:
            - default-windows
