trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - samples/policies/vsts-agent
pr: none

stages:
  - template: ../azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: vsts-agent
          platforms:
            - windows-core-windows
            - ubuntu-core-ubuntu
            - ubuntu-virtualbox-ubuntu
