driver:
  name: vagrant
  vm_hostname: false
  customize:
    cpus: 2
    memory: 2048

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      box: gusztavvargadr/windows-server

  - name: ubuntu
    driver:
      box: gusztavvargadr/ubuntu-server

suites:
  - name: app
    provisioner:
      named_run_list: app
