driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      vagrantfiles:
        - ../vagrant.windows-server.rb

  - name: ubuntu
    driver:
      vagrantfiles:
        - ../vagrant.ubuntu-server.rb

suites:
  - name: app
    provisioner:
      named_run_list: app
