driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      box: gusztavvargadr/windows-server
      vagrantfiles:
        - ../vagrant.rb
  - name: ubuntu
    driver:
      box: gusztavvargadr/ubuntu-server
      vagrantfiles:
        - ../vagrant.rb

suites:
  - name: app
    run_list:
      - recipe[gusztavvargadr_vagrant_test::app]
