directory = File.dirname(__FILE__)

require "#{directory}/../../../src/berkshelf"

gusztavvargadr_chef_sources

gusztavvargadr_chef_cookbook 'vagrant_test'
gusztavvargadr_chef_cookbook 'vagrant'
gusztavvargadr_chef_cookbook 'windows'
