driver:
  name: vagrant
  vagrantfiles:
    - ../../../src/kitchen.vagrant
  provider: <%= ENV['VAGRANT_PREFERRED_PROVIDERS'] || ENV['VAGRANT_DEFAULT_PROVIDER'] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      box: <%= ENV['VAGRANT_BOX_WINDOWS_DESKTOP'] || 'gusztavvargadr/windows-10' %>

suites:
  - name: 2017-community
    run_list:
      - recipe[gusztavvargadr_visualstudio_test::2017_community]
  - name: 2017-professional
    run_list:
      - recipe[gusztavvargadr_visualstudio_test::2017_professional]
