driver:
  name: vagrant

provisioner:
  name: chef_zero
  wait_for_retry: 300

verifier:
  name: inspec

platforms:
  - name: windows
    driver:
      box: gusztavvargadr/windows-server
      vagrantfiles:
        - ../vagrant.rb

suites:
  - name: 2017-community
    run_list:
      - recipe[gusztavvargadr_visualstudio_test::2017_community]

  - name: 2017-professional
    run_list:
      - recipe[gusztavvargadr_visualstudio_test::2017_professional]

  - name: 2019-community
    run_list:
      - recipe[gusztavvargadr_visualstudio_test::2019_community]

  - name: 2019-professional
    run_list:
      - recipe[gusztavvargadr_visualstudio_test::2019_professional]
