require "#{File.dirname(__FILE__)}/../../../../src/vagrant"

VagrantProvider.defaults(
  'memory' => 4096,
  'cpus' => 2
)

deployment = VagrantDeployment.new(File.dirname(__FILE__))
deployment.configure
