parameters:
  configurations: []
    # - name: string
    #   instances: [ string ]

stages:
  - stage: commit
    displayName: Commit

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - job: build_${{ replace(configuration.name, '-', '_') }}
          displayName: Build policy ${{ configuration.name }}

          pool:
            name: default

          workspace:
            clean: all

          steps:
            - checkout: self
              submodules: recursive

            - script: |
                chef install ./samples/policies/${{ configuration.name }}/Policyfile.rb
                chef export ./samples/policies/${{ configuration.name }}/Policyfile.rb ./artifacts/policies/${{ configuration.name }}/ --force
                cp ./samples/policies/${{ configuration.name }}/attributes.* ./artifacts/policies/${{ configuration.name }}/ || true
              displayName: Build

            - publish: $(Build.SourcesDirectory)/artifacts/
              displayName: Publish Artifacts
              artifact: build-${{ configuration.name }}

  - stage: acceptance
    displayName: Acceptance

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - ${{ each instance in configuration.instances }}:
          - job: test_${{ replace(configuration.name, '-', '_') }}_${{ replace(instance, '-', '_') }}
            displayName: Test policy ${{ configuration.name }} on instance ${{ instance }}

            pool:
              ${{ if contains(instance, 'windows') }}:
                name: windows-2022-hyperv
              ${{ else }}:
                name: ubuntu-2204-virtualbox

            workspace:
              clean: all

            steps:
              - checkout: self
                submodules: recursive

              - script: |
                  chef --version
                displayName: Initialize Chef

              - script: |
                  vagrant --version
                  vagrant plugin list

                  vagrant box list
                  vagrant global-status --prune
                displayName: Initialize Vagrant

              - script: |
                  cd samples/policies/${{ configuration.name }}
                  kitchen test ${{ instance }}
                displayName: Test

              - script: |
                  cd samples/policies/${{ configuration.name }}
                  kitchen create ${{ instance }}
                displayName: Create
                condition: not(succeeded())

              - script: |
                  cd samples/policies/${{ configuration.name }}
                  kitchen destroy ${{ instance }}
                displayName: Clean
                condition: always()

  - stage: release
    displayName: Release

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - job: publish_${{ replace(configuration.name, '-', '_') }}
          displayName: Publish policy ${{ configuration.name }}

          pool:
            name: default

          workspace:
            clean: all

          steps:
            - checkout: self
              submodules: recursive

            - task: DownloadPipelineArtifact@2
              displayName: Download Artifacts
              inputs:
                artifact: build-${{ configuration.name }}
                path: $(Build.SourcesDirectory)/artifacts/

            - script: |
                tar -czf ./artifacts/policies/${{ configuration.name }}.tgz -C ./artifacts/policies/${{ configuration.name }}/ .
                rm -Rf ./artifacts/policies/${{ configuration.name }}/
              displayName: Package

            - publish: $(Build.SourcesDirectory)/artifacts/
              displayName: Publish Artifacts
              artifact: publish-${{ configuration.name }}
