parameters:
  configurations: []
    # - name: string
    #   platforms: [ string ]

stages:
  - stage: commit
    displayName: Commit

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - job: build_${{ replace(configuration.name, '-', '_') }}
          displayName: Build ${{ configuration.name }}

          pool:
            name: core-linux

          steps:
            - checkout: self
              submodules: recursive

            - script: |
                chef --version
              displayName: Initialize Chef

            - script: |
                chef install ./samples/policies/${{ configuration.name }}/Policyfile.rb
                chef export ./samples/policies/${{ configuration.name }}/Policyfile.rb ./artifacts/policies/${{ configuration.name }}/ --force
              displayName: Build

            - publish: $(Build.SourcesDirectory)/artifacts/
              displayName: Publish Artifacts
              artifact: build-${{ configuration.name }}

  - stage: acceptance
    displayName: Acceptance

    jobs:
      - ${{ each configuration in parameters.configurations }}:
        - ${{ each platform in configuration.platforms }}:
          - job: test_${{ replace(configuration.name, '-', '_') }}_${{ replace(platform, '-', '_') }}
            displayName: Test ${{ configuration.name }} on ${{ platform }}

            pool:
              name: virtualbox-linux

            # ${{ if contains(platform, 'ubuntu') }}:
            #   pool:
            #     name: virtualbox-linux
            # ${{ elseif contains(platform, 'windows') }}:
            #   pool:
            #     name: hyperv-windows
            # ${{ else }}:
            #   pool:
            #     name: Default
            #     demands:
            #       - VSTS_AGENT_CAP_HYPERVISOR

            steps:
              - checkout: self
                submodules: recursive

              - script: |
                  chef --version
                displayName: Initialize Chef

              - script: |
                  vagrant --version
                  vagrant plugin list

                  vagrant box list
                  vagrant global-status --prune
                displayName: Initialize Vagrant

              - task: DownloadPipelineArtifact@2
                displayName: Download Artifacts
                inputs:
                  artifact: build-${{ configuration.name }}
                  path: $(Build.SourcesDirectory)/artifacts/

              - script: |
                  cd samples/policies/${{ configuration.name }}
                  kitchen test ${{ platform }}
                displayName: Test

              - script: |
                  cd samples/policies/${{ configuration.name }}
                  kitchen destroy ${{ platform }}
                displayName: Clean
                condition: always()
