directory = File.dirname(__FILE__)

require "#{directory}/../vagrant"

VagrantMachine.defaults_include(
  'box' => VagrantWindowsDesktopMachine.defaults['box']
)

VagrantProvider.defaults_include(
  'memory' => 4096,
  'cpus' => 2
)

VagrantDeployment.configure(directory, 'component' => 'policies')
